name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/eeeeeeeeee-code/POC.git || echo "上游仓库已存在"
          git fetch upstream

      - name: 合并上游变更（不会删除你的内容）
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "无新变更"

      - name: 推送到你的 GitHub 仓库
        run: |
          git push origin main
