name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的仓库（使用 GitHub Token）
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 避免使用默认 Git 凭据
          fetch-depth: 0  # 获取完整历史，以确保 merge 操作可用

      - name: 设置 Git 用户信息
        run: |
          git config --global user.name "Gavin2233"
          git config --global user.email "852614921@qq.com"

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/eeeeeeeeee-code/POC.git || echo "上游仓库已存在"
          git fetch upstream

      - name: 合并上游变更（不会删除你的内容）
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "无新变更"

      - name: 推送到你的 GitHub 仓库（使用 GitHub Token）
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
